import type { Metadata } from "next";

import { StaticPage } from "@/components/static-page";
import { buildPageMetadata } from "@/lib/seo/page-utils";

export const metadata: Metadata = buildPageMetadata({
  title: "Terms of Service",
  description:
    "The terms and conditions for using HueFlow's color tools, palettes, gradients, and content.",
  path: "/terms",
});

const CONTACT_EMAIL = "suvagiyaaganik@gmail.com";

export default function TermsPage() {
  return (
    <StaticPage title="Terms of Service" updated="July 26, 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of HueFlow
        at hueflow.site (the &quot;Site&quot;). By accessing or using the Site,
        you agree to be bound by these Terms. If you do not agree, please do
        not use the Site.
      </p>

      <h2>Use of the Site</h2>
      <p>
        HueFlow provides color tools, palettes, gradients, guides, and related
        content for designers, developers, and marketers. You may use the Site
        for personal and commercial projects, subject to these Terms. You agree
        not to:
      </p>
      <ul>
        <li>Use the Site in any way that violates applicable laws.</li>
        <li>
          Attempt to disrupt, overload, or interfere with the Site or its
          infrastructure, including automated scraping at abusive volumes.
        </li>
        <li>
          Misrepresent the Site or its content as your own product or service.
        </li>
      </ul>

      <h2>Colors, Palettes, and Generated Output</h2>
      <p>
        Individual colors are not copyrightable, and you are free to use
        colors, palettes, gradients, and code snippets generated by HueFlow in
        your own projects - personal or commercial - without attribution.
      </p>

      <h2>Site Content</h2>
      <p>
        The articles, guides, design, and branding of the Site are owned by
        HueFlow. You may not republish substantial portions of the Site&apos;s
        written content without permission. Linking to and quoting pages with
        attribution is welcome.
      </p>

      <h2>No Warranty</h2>
      <p>
        The Site and its tools are provided &quot;as is&quot; and &quot;as
        available&quot; without warranties of any kind, express or implied. We
        do not guarantee that the Site will be uninterrupted, error-free, or
        that results (such as contrast ratios or accessibility checks) are
        suitable for any particular purpose. Always verify accessibility and
        compliance requirements independently for production use.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, HueFlow shall not be liable for
        any indirect, incidental, special, consequential, or punitive damages
        arising out of your use of, or inability to use, the Site.
      </p>

      <h2>Third-Party Services and Advertising</h2>
      <p>
        The Site may display advertisements and link to third-party websites.
        We are not responsible for the content, policies, or practices of
        third-party sites or advertisers. See our{" "}
        <a href="/privacy">Privacy Policy</a> for details on advertising and
        analytics.
      </p>

      <h2>Changes to the Site and Terms</h2>
      <p>
        We may modify or discontinue any part of the Site at any time. We may
        also update these Terms; continued use of the Site after changes are
        posted constitutes acceptance of the updated Terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these Terms? Contact us at{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
    </StaticPage>
  );
}
