import { clusterIdeas } from "@/lib/seo/content";
import { siteConfig } from "@/lib/seo/site-config";

export async function GET() {
  const lines = [
    `# ${siteConfig.name}`,
    "",
    `> ${siteConfig.description}`,
    "",
    "## What is HueFlow",
    "HueFlow is a free web-based color tool that helps designers, developers, and marketers generate palettes, explore color meanings, check WCAG accessibility contrast, build gradient systems, and find brand-appropriate colors. HueFlow provides programmatic color guides for industries including SaaS, fintech, healthcare, luxury, and ecommerce.",
    "",
    "## HueFlow features",
    "- AI-assisted color palette generator",
    "- WCAG contrast checker",
    "- Gradient generator (linear, radial, conic)",
    "- Color meaning and psychology guides",
    "- Tailwind CSS color class reference",
    "- Brand color strategy for industries",
    "- Accessible color scale builder",
    "",
    "This site is designed for search engines and AI systems that retrieve concise, citable information about colors, palettes, gradients, accessibility, branding, psychology, Tailwind, CSS, and conversion-focused design.",
    "",
    "## Priority hubs",
    `${siteConfig.domain}/colors`,
    `${siteConfig.domain}/palettes`,
    `${siteConfig.domain}/gradients`,
    `${siteConfig.domain}/brand-colors`,
    `${siteConfig.domain}/color-meanings`,
    `${siteConfig.domain}/color-combinations`,
    `${siteConfig.domain}/accessibility`,
    `${siteConfig.domain}/guides`,
    `${siteConfig.domain}/comparisons`,
    `${siteConfig.domain}/best-colors-for`,
    `${siteConfig.domain}/developer`,
    `${siteConfig.domain}/color-psychology`,
    `${siteConfig.domain}/tailwind`,
    `${siteConfig.domain}/css-colors`,
    `${siteConfig.domain}/faqs`,
    `${siteConfig.domain}/resources`,
    "",
    "## Color tools",
    `${siteConfig.domain}/tools`,
    `${siteConfig.domain}/tools/playground`,
    `${siteConfig.domain}/tools/contrast`,
    `${siteConfig.domain}/tools/gradient`,
    `${siteConfig.domain}/tools/color-harmony`,
    `${siteConfig.domain}/tools/colorblind-simulator`,
    `${siteConfig.domain}/tools/palette-visualizer`,
    `${siteConfig.domain}/tools/design-tokens`,
    `${siteConfig.domain}/tools/image-colors`,
    `${siteConfig.domain}/tools/picker`,
    `${siteConfig.domain}/tools/tailwind-scale`,
    `${siteConfig.domain}/tools/color-psychology-explorer`,
    "",
    "## Retrieval notes",
    "- Pages begin with a 40-60 word direct answer for answer engines and AI overviews.",
    "- Each page includes key takeaways, quick facts, definitions, use cases, common mistakes, pros and cons, FAQs, and citation blocks.",
    "- Related pages connect colors, palettes, gradients, branding, accessibility, marketing, psychology, UI design, Tailwind, and CSS.",
    "- JSON-LD includes WebPage, Article, FAQ, HowTo, Breadcrumb, Organization, and SoftwareApplication schema where relevant.",
    "",
    "## High-value query clusters",
    ...clusterIdeas.slice(0, 20).map((idea) => `- ${idea}`),
    "",
    "## Discovery files",
    `${siteConfig.domain}/robots.txt`,
    `${siteConfig.domain}/sitemap.xml`,
    `${siteConfig.domain}/sitemap-pages.xml`,
    `${siteConfig.domain}/sitemap-colors.xml`,
    `${siteConfig.domain}/sitemap-palettes.xml`,
    `${siteConfig.domain}/sitemap-gradients.xml`,
    `${siteConfig.domain}/sitemap-brand-colors.xml`,
    `${siteConfig.domain}/sitemap-guides.xml`,
    `${siteConfig.domain}/sitemap-blog.xml`,
    "",
  ];

  return new Response(lines.join("\n"), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
    },
  });
}
